<?xml version="1.0"?>
<robot name="dokalman" xmlns:xacro="http://ros.org/wiki/xacro">
<!-- Define robot constants -->
<xacro:property name="base_width" value="0.31"/>
<xacro:property name="base_length" value="0.42"/>
<xacro:property name="base_height" value="0.18"/>

<xacro:property name="wheel_radius" value="0.155"/>
<xacro:property name="wheel_width" value="0.04"/>
<xacro:property name="wheel_ygap" value="0.11"/>
<xacro:property name="wheel_zoff" value="0.00"/>
<xacro:property name="wheel_xoff" value="0.0"/>

<xacro:property name="caster_xoff" value="0.5"/>

<!-- Robot Base -->
<link name="base_link">
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="8"/>
    <inertia ixx="0.56" ixy="0" ixz="0" iyy="0.38" iyz="0" izz="0.21"/>
  </inertial>
  <visual>
    <origin xyz="0 0 0" rpy="0 0 1.5708"/> <!-- 1.5708 radians = 90 degrees -->
    <geometry>
      <mesh filename="package://dokalman/meshes/base_link.STL"/>
    </geometry>
    <material name="Gray">
      <color rgba="0.5 0.5 0.5 1.0"/>
    </material>
  </visual>
</link>

<!-- Robot Footprint -->
<link name="base_footprint"/>

<joint name="base_joint" type="fixed">
  <parent link="base_link"/>
  <child link="base_footprint"/>
  <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
</joint>

<!-- Wheels -->
<xacro:macro name="wheel" params="prefix x_reflect y_reflect">
  <link name="${prefix}_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="0.0008" ixy="0" ixz="0" iyy="0.0008" iyz="0" izz="0.00015"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="${prefix}_joint" type="continuous">
    <parent link="base_link"/>
    <child link="${prefix}_link"/>
    <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
</xacro:macro>

<xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />
<xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />

<!-- Caster Wheel -->
<link name="front_caster">
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="0.5"/>
    <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0002"/>
  </inertial>
  <visual>
    <origin xyz="-0.05 0 -0.16" rpy="1.5708 0 1.5708"/> <!-- 1.5708 radians = 90 degrees -->
    <geometry>
      <mesh filename="package://dokalman/meshes/Caster.STL"/>
    </geometry>
    <material name="Gray">
      <color rgba="0 1.0 1.0 1.0"/>
    </material>
  </visual>
</link>

<joint name="caster_joint" type="fixed">
  <parent link="base_link"/>
  <child link="front_caster"/>
  <origin xyz="${caster_xoff} 0.0 0" rpy="0 0 0"/>
</joint>

<!-- GPS -->
<link name="back_gps">
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="0.1"/>
    <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000002"/>
  </inertial>
  <visual>
    <origin xyz="-0.025 0.025 0" rpy="1.5708 0 1.5708"/> <!-- 1.5708 radians = 90 degrees -->
    <geometry>
      <mesh filename="package://dokalman/meshes/FrontGPS.STL"/>
    </geometry>
    <material name="Gray">
      <color rgba="0 1.0 1.0 1.0"/>
    </material>
  </visual>
</link>

<joint name="back_gps_joint" type="fixed">
  <parent link="base_link"/>
  <child link="back_gps"/>
  <origin xyz="0.0 0.0 0.465" rpy="0 0 0"/>
</joint>

<link name="front_gps">
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="0.1"/>
    <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000002"/>
  </inertial>
  <visual>
    <origin xyz="0.025 -0.025 0" rpy="1.5708 0 -1.5708"/> <!-- 1.5708 radians = 90 degrees -->
    <geometry>
      <mesh filename="package://dokalman/meshes/BackGPS.STL"/>
    </geometry>
    <material name="Gray">
      <color rgba="0 1.0 1.0 1.0"/>
    </material>
  </visual>
</link>

<joint name="front_gps_joint" type="fixed">
  <parent link="base_link"/>
  <child link="front_gps"/>
  <origin xyz="0.6 0.0 0.465" rpy="0 0 0"/>
</joint>

<!-- CAMERAS -->
<link name="left_cam">
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="0.2"/>
    <inertia ixx="0.000005" ixy="0" ixz="0" iyy="0.000005" iyz="0" izz="0.00001"/>
  </inertial>
  <visual>
    <origin xyz="0.01 0.02 0.025" rpy="1.5708 0 1.5708"/> <!-- 1.5708 radians = 90 degrees -->
    <geometry>
      <mesh filename="package://dokalman/meshes/FLCam.STL"/>
    </geometry>
    <material name="Gray">
      <color rgba="0 1.0 1.0 1.0"/>
    </material>
  </visual>
</link>

<joint name="left_cam_joint" type="fixed">
  <parent link="base_link"/>
  <child link="left_cam"/>
  <origin xyz="0.5 -0.16 0.465" rpy="0 0 -1"/>
</joint>

<link name="right_cam">
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="0.2"/>
    <inertia ixx="0.000005" ixy="0" ixz="0" iyy="0.000005" iyz="0" izz="0.00001"/>
  </inertial>
  <visual>
    <origin xyz="0.01 0.02 0.025" rpy="1.5708 0 1.5708"/> <!-- 1.5708 radians = 90 degrees -->
    <geometry>
      <mesh filename="package://dokalman/meshes/FRCam.STL"/>
    </geometry>
    <material name="Gray">
      <color rgba="0 1.0 1.0 1.0"/>
    </material>
  </visual>
</link>

<joint name="right_cam_joint" type="fixed">
  <parent link="base_link"/>
  <child link="right_cam"/>
  <origin xyz="0.5 0.16 0.465" rpy="0 0 1"/>
</joint>

</robot>

